### ISSUE TITLE
Acceptance test intermittent fails in editTextFiles.feature

### ISSUE THREAD

**Issue by phil-davis** [owncloud/files_texteditor#280]
This scenario fails intermittently:
https://drone.owncloud.com/owncloud/files_texteditor/113/135
```
  Scenario: Edit a text file with the default name and file extension in a sub-folder # /var/www/owncloud/apps/files_texteditor/tests/acceptance/features/webUITextEditor/editTextFiles.feature:11
    When the user opens folder "simple-folder" using the webUI                        # WebUIFilesContext::theUserOpensFolderNamedUsingTheWebUI()
    And the user creates a text file with the name "" using the webUI                 # TextEditorContext::createATextFileWithTheNameUsingTheWebUI()
    And the user inputs "stuff" in the text area                                      # TextEditorContext::theUserInputsTextInTheTextArea()
INFORMATION: timed out waiting for ajax calls to start
    And the user closes the text editor                                               # TextEditorContext::theUserClosesTheTextEditor()
      │ INFORMATION: timed out waiting for ajax calls to start
    Then file "New text file.txt" should be listed on the webUI                       # WebUIFilesContext::fileFolderShouldBeListedOnTheWebUI()
    And the user reloads the current page of the webUI                                # WebUIGeneralContext::theUserReloadsTheCurrentPageOfTheWebUI()
    Then file "New text file.txt" should be listed on the webUI                       # WebUIFilesContext::fileFolderShouldBeListedOnTheWebUI()
    And the user opens file "New text file.txt" using the webUI                       # WebUIFilesContext::theUserOpensFolderNamedUsingTheWebUI()
    Then line 1 of the text should be "stuff"                                         # TextEditorContext::lineOfTheTextShouldBe()
    And the user inputs "other text before " in the text area                         # TextEditorContext::theUserInputsTextInTheTextArea()
INFORMATION: timed out waiting for ajax calls to start
    And the user closes the text editor                                               # TextEditorContext::theUserClosesTheTextEditor()
      │ INFORMATION: timed out waiting for ajax calls to start
    And the user opens file "New text file.txt" using the webUI                       # WebUIFilesContext::theUserOpensFolderNamedUsingTheWebUI()
      WebDriver\Exception\StaleElementReference: stale element reference: element is not attached to the page document
        (Session info: chrome=71.0.3578.98)
        (Driver info: chromedriver=2.45.615279 (12b89733300bd268cff3b78fc76cb8f3a7cc44e5),platform=Linux 4.4.0-140-generic x86_64) in /var/www/owncloud/apps/files_texteditor/vendor-bin/behat/vendor/instaclick/php-webdriver/lib/WebDriver/Exception.php:155
      Stack trace:
      #0 /var/www/owncloud/apps/files_texteditor/vendor-bin/behat/vendor/instaclick/php-webdriver/lib/WebDriver/AbstractWebDriver.php(157): WebDriver\Exception::factory(10, 'stale element r...')
      #1 /var/www/owncloud/apps/files_texteditor/vendor-bin/behat/vendor/instaclick/php-webdriver/lib/WebDriver/AbstractWebDriver.php(218): WebDriver\AbstractWebDriver->curl('POST', '/execute', Array)
      #2 /var/www/owncloud/apps/files_texteditor/vendor-bin/behat/vendor/instaclick/php-webdriver/lib/WebDriver/Container.php(224): WebDriver\AbstractWebDriver->__call('execute', Array)
      #3 /var/www/owncloud/apps/files_texteditor/vendor-bin/behat/vendor/behat/mink-selenium2-driver/src/Selenium2Driver.php(288): WebDriver\Container->__call('execute', Array)
      #4 /var/www/owncloud/apps/files_texteditor/vendor-bin/behat/vendor/behat/mink-selenium2-driver/src/Selenium2Driver.php(263): Behat\Mink\Driver\Selenium2Driver->executeJsOnElement(Object(WebDriver\Element), 'Syn.trigger("fo...', true)
      #5 /var/www/owncloud/apps/files_texteditor/vendor-bin/behat/vendor/behat/mink-selenium2-driver/src/Selenium2Driver.php(1144): Behat\Mink\Driver\Selenium2Driver->executeJsOnXpath('((//html/.//div...', 'Syn.trigger("fo...')
      #6 /var/www/owncloud/apps/files_texteditor/vendor-bin/behat/vendor/behat/mink-selenium2-driver/src/Selenium2Driver.php(846): Behat\Mink\Driver\Selenium2Driver->trigger('((//html/.//div...', 'focus')
      #7 /var/www/owncloud/apps/files_texteditor/vendor-bin/behat/vendor/behat/mink/src/Element/NodeElement.php(297): Behat\Mink\Driver\Selenium2Driver->focus('((//html/.//div...')
      #8 /var/www/owncloud/tests/acceptance/features/lib/FilesPageBasic.php(155): Behat\Mink\Element\NodeElement->focus()
      #9 /var/www/owncloud/tests/acceptance/features/lib/FilesPageBasic.php(277): Page\FilesPageBasic->getFileRowElementsByName('New text file.t...', Object(Behat\Mink\Session))
      #10 /var/www/owncloud/tests/acceptance/features/lib/FilesPageBasic.php(239): Page\FilesPageBasic->findAllFileRowsByName('New text file.t...', Object(Behat\Mink\Session))
      #11 /var/www/owncloud/tests/acceptance/features/lib/FilesPageBasic.php(333): Page\FilesPageBasic->findFileRowByName('New text file.t...', Object(Behat\Mink\Session))
      #12 /tmp/ProxyManagerGeneratedProxy__PM__PageFilesPageGenerated2897994410194442686143097669da61.php(254): Page\FilesPageBasic->openFile('New text file.t...', Object(Behat\Mink\Session))
      #13 /var/www/owncloud/tests/acceptance/features/bootstrap/WebUIFilesContext.php(1243): ProxyManagerGeneratedProxy\__PM__\Page\FilesPage\Generated2897994410194442686143097669da61->openFile('New text file.t...', Object(Behat\Mink\Session))
      #14 /var/www/owncloud/tests/acceptance/features/bootstrap/WebUIFilesContext.php(1199): WebUIFilesContext->theUserOpensTheFileOrFolderUsingTheWebUI('', 'file', 'New text file.t...')
      #15 [internal function]: WebUIFilesContext->theUserOpensFolderNamedUsingTheWebUI('', 'file', '"New text file....')
```

``theUserOpensTheFileOrFolderUsingTheWebUI`` in core has been refactored recently, and it (like other acceptance test methods) expects the files page to be ready when it is called.

But ``And the user closes the text editor`` just clicks the close button and does not wait until the editor is really closed.

IMO it should be the responsibility of the text editor acceptance test code to wait nicely until the editor is closed, because that is the code that has the knowledge of the various ``xpath`` etc of the test editor page elements.

**Comment by individual-it** [comment]
Fixed by #281
